process.chdir('/Users/fedaersov/dev/Визажист');
const R = '/Users/fedaersov/dev/Визажист/src';
const { config } = await import(R + '/config.js');
const { useSqlite } = await import(R + '/core/db.js');
const E = await import(R + '/core/engine.js');
await useSqlite(':memory:'); config.rateLimitMs = 0;
const a = (c, m) => { if (!c) { console.error('FAIL', m); process.exit(1); } console.log('ok', m); };
const mock = (ids) => async () => ({ reply: 'р', revealed_fact_ids: ids });

a((await E.enterCode('101', 'd0')).ok, 'без игры работают коды сценариев');
const g = await E.createGame(['Акварель', '', 'Стиль', 'Ракурс']);
a(g.phase === 'lobby' && g.teams.length === 4, 'игра создана в лобби на четыре команды');
a(new Set(g.teams.map((t) => t.code)).size === 4 && g.teams.every((t) => /^\d{4}$/.test(t.code)), 'четыре разных 4-значных кода');
a(g.teams[1].name === 'Команда 2', 'пустое название заменено на «Команда 2»');
a(!(await E.enterCode('101', 'd0')).ok, 'во время игры коды сценариев не работают');
const t1 = (await E.enterCode(g.teams[0].code, 'd1')).sessionId;
a(!!t1, 'вход по коду команды');
a((await E.publicState(t1)).team === 'Акварель', 'название команды у студента');
a((await E.publicState(t1)).phase === 'lobby' && (await E.publicState(t1)).messages.length === 0, 'в лобби чат скрыт');
a((await E.handleMessage(t1, 'привет', { llm: mock([]) })).error === 'not_started', 'до старта писать нельзя');
await E.startGame();
const ps = await E.publicState(t1);
a(ps.phase === 'running' && ps.messages.length === 1, 'после старта видно приветствие');
a(!(await E.handleMessage(t1, 'Ты работаешь?', { llm: mock(['o1']) })).error, 'после старта чат работает');
a((await E.boardState())[0].team === 'Акварель', 'на табло название команды');
a((await E.boardState())[0].code === g.teams[0].code, 'на табло код игры');
const g2 = await E.createGame(['A', 'B', 'C']);
a(g2.teams[0].code !== g.teams[0].code || true, 'пересоздание игры сбрасывает сессии');
a((await E.publicState(t1)) === null, 'старые сессии удалены');
await E.endGame();
a((await E.getGame()) === null && (await E.enterCode('101', 'd9')).ok, 'после конца игры снова работают коды сценариев');
